/**
 * Tokens-to-CSS Generator
 *
 * Converts unified design tokens into CSS custom properties.
 * This is the style sheet that gets injected into an Astro theme.
 */

/**
 * Generate a complete CSS file from unified tokens
 * @param {object} tokens - Unified token object from style-to-tokens.js
 * @returns {string} CSS string with :root variables and component classes
 */
export function generateCSS(tokens) {
  const lines = [];

  lines.push('/* ============================================');
  lines.push(`   Style Set Theme: ${tokens.meta?.name || 'Custom Theme'}`);
  lines.push(`   Style: ${tokens.meta?.style || 'custom'}`);
  lines.push('   Generated by Style Set (styleset.app)');
  lines.push('   ============================================ */');
  lines.push('');

  // CSS Custom Properties
  lines.push(':root {');
  lines.push('  /* ---- Colors: Brand ---- */');
  lines.push(...colorVars('brand', tokens.colors.brand));
  lines.push('');
  lines.push('  /* ---- Colors: Surface ---- */');
  lines.push(...colorVars('surface', tokens.colors.surface));
  lines.push('');
  lines.push('  /* ---- Colors: Text ---- */');
  lines.push(...colorVars('text', tokens.colors.text));
  lines.push('');
  lines.push('  /* ---- Colors: Border ---- */');
  lines.push(...colorVars('border', tokens.colors.border));
  lines.push('');
  lines.push('  /* ---- Colors: Status ---- */');
  lines.push(...colorVars('status', tokens.colors.status));
  lines.push('');
  lines.push('  /* ---- Colors: Accent ---- */');
  lines.push(...colorVars('accent', tokens.colors.accent));
  lines.push('');

  // Typography
  lines.push('  /* ---- Typography ---- */');
  if (tokens.typography.fontFamily.sans) {
    lines.push(`  --font-sans: '${tokens.typography.fontFamily.sans}', ui-sans-serif, system-ui, sans-serif;`);
  }
  if (tokens.typography.fontFamily.serif) {
    lines.push(`  --font-serif: '${tokens.typography.fontFamily.serif}', ui-serif, Georgia, serif;`);
  }
  if (tokens.typography.fontFamily.mono) {
    lines.push(`  --font-mono: '${tokens.typography.fontFamily.mono}', ui-monospace, monospace;`);
  }
  lines.push('');
  lines.push('  /* Font Sizes */');
  for (const [key, val] of Object.entries(tokens.typography.fontSize)) {
    if (val) lines.push(`  --text-${key}: ${val};`);
  }
  lines.push('');
  lines.push('  /* Font Weights */');
  for (const [key, val] of Object.entries(tokens.typography.fontWeight)) {
    if (val) lines.push(`  --font-${key}: ${val};`);
  }
  lines.push('');
  lines.push('  /* Line Heights */');
  for (const [key, val] of Object.entries(tokens.typography.lineHeight)) {
    if (val) lines.push(`  --leading-${key}: ${val};`);
  }
  lines.push('');

  // Spacing
  lines.push('  /* ---- Spacing ---- */');
  lines.push(`  --space-unit: ${tokens.spacing.base};`);
  const base = parseInt(tokens.spacing.base) || 8;
  lines.push(`  --space-xs: ${base * 0.5}px;`);
  lines.push(`  --space-sm: ${base}px;`);
  lines.push(`  --space-md: ${base * 2}px;`);
  lines.push(`  --space-lg: ${base * 3}px;`);
  lines.push(`  --space-xl: ${base * 4}px;`);
  lines.push(`  --space-2xl: ${base * 6}px;`);
  lines.push('');

  // Borders
  lines.push('  /* ---- Borders ---- */');
  for (const [key, val] of Object.entries(tokens.borders.radius)) {
    if (val) lines.push(`  --radius-${key === 'DEFAULT' ? 'base' : key}: ${val};`);
  }
  for (const [key, val] of Object.entries(tokens.borders.width)) {
    if (val) lines.push(`  --border-${key === 'DEFAULT' ? 'base' : key}: ${val};`);
  }
  lines.push('');

  // Shadows
  lines.push('  /* ---- Shadows ---- */');
  for (const [key, val] of Object.entries(tokens.shadows)) {
    if (val) lines.push(`  --shadow-${key === 'DEFAULT' ? 'base' : key}: ${val};`);
  }
  lines.push('');

  // Effects
  lines.push('  /* ---- Effects ---- */');
  if (tokens.effects.blur) {
    for (const [key, val] of Object.entries(tokens.effects.blur)) {
      if (val) lines.push(`  --blur-${key === 'DEFAULT' ? 'base' : key}: ${val};`);
    }
  }
  if (tokens.effects.transition) {
    for (const [key, val] of Object.entries(tokens.effects.transition)) {
      if (val) lines.push(`  --transition-${key === 'DEFAULT' ? 'base' : key}: ${val};`);
    }
  }

  lines.push('}');
  lines.push('');

  // Component classes
  lines.push(generateComponentCSS(tokens));

  return lines.join('\n');
}

function colorVars(prefix, colorObj) {
  const lines = [];
  if (!colorObj) return lines;
  for (const [key, val] of Object.entries(colorObj)) {
    if (val) {
      const name = key === 'DEFAULT' ? prefix : `${prefix}-${key}`;
      lines.push(`  --color-${name}: ${val};`);
    }
  }
  return lines;
}

function generateComponentCSS(tokens) {
  const style = tokens.meta?.style || 'minimalism';
  const lines = [];

  lines.push('/* ---- Base Reset ---- */');
  lines.push('*, *::before, *::after { box-sizing: border-box; }');
  lines.push('');

  lines.push('body {');
  lines.push('  font-family: var(--font-sans);');
  lines.push('  font-size: var(--text-body);');
  lines.push('  font-weight: var(--font-body);');
  lines.push('  line-height: var(--leading-normal);');
  lines.push('  color: var(--color-text-primary);');
  lines.push('  background-color: var(--color-surface-canvas);');
  lines.push('}');
  lines.push('');

  // Headings
  lines.push('h1 { font-size: var(--text-h1); font-weight: var(--font-heading); line-height: var(--leading-tight); }');
  lines.push('h2 { font-size: var(--text-h2); font-weight: var(--font-heading); line-height: var(--leading-tight); }');
  lines.push('h3 { font-size: var(--text-h3); font-weight: var(--font-heading); line-height: var(--leading-tight); }');
  lines.push('');

  // Card component
  lines.push('.card {');
  lines.push('  background: var(--color-surface-base);');
  lines.push('  border-radius: var(--radius-base);');
  lines.push('  padding: var(--space-lg);');
  lines.push(`  border: var(--border-base) solid var(--color-border);`);
  lines.push('  box-shadow: var(--shadow-base);');
  lines.push('  transition: var(--transition-base);');
  if (style === 'glassmorphism') {
    lines.push('  backdrop-filter: blur(var(--blur-base));');
    lines.push('  -webkit-backdrop-filter: blur(var(--blur-base));');
  }
  lines.push('}');
  lines.push('');
  lines.push('.card:hover {');
  lines.push('  box-shadow: var(--shadow-md);');
  lines.push('}');
  lines.push('');

  // Button component
  lines.push('.btn {');
  lines.push('  display: inline-flex;');
  lines.push('  align-items: center;');
  lines.push('  justify-content: center;');
  lines.push('  padding: var(--space-sm) var(--space-lg);');
  lines.push('  font-weight: var(--font-bold);');
  lines.push('  font-size: var(--text-body);');
  lines.push('  border-radius: var(--radius-sm);');
  lines.push('  transition: var(--transition-base);');
  lines.push('  cursor: pointer;');
  lines.push('  border: var(--border-base) solid transparent;');
  lines.push('}');
  lines.push('');
  lines.push('.btn-primary {');
  lines.push('  background: var(--color-brand);');
  lines.push('  color: var(--color-surface-canvas);');
  if (style === 'brutalism' || style === 'neubrutalism') {
    lines.push('  border-color: var(--color-border);');
    lines.push('  box-shadow: var(--shadow-base);');
  }
  lines.push('}');
  lines.push('');
  lines.push('.btn-primary:hover {');
  lines.push('  background: var(--color-brand-dark);');
  if (style === 'brutalism' || style === 'neubrutalism') {
    lines.push('  transform: translate(2px, 2px);');
    lines.push('  box-shadow: var(--shadow-sm);');
  }
  lines.push('}');
  lines.push('');
  lines.push('.btn-secondary {');
  lines.push('  background: var(--color-surface-muted);');
  lines.push('  color: var(--color-text-primary);');
  lines.push('  border-color: var(--color-border);');
  lines.push('}');
  lines.push('');

  // Input component
  lines.push('.input {');
  lines.push('  width: 100%;');
  lines.push('  padding: var(--space-sm) var(--space-md);');
  lines.push('  font-size: var(--text-body);');
  lines.push('  font-family: var(--font-sans);');
  lines.push('  background: var(--color-surface-muted);');
  lines.push('  border: var(--border-base) solid var(--color-border-subtle);');
  lines.push('  border-radius: var(--radius-sm);');
  lines.push('  color: var(--color-text-primary);');
  lines.push('  transition: var(--transition-base);');
  if (style === 'neomorphism') {
    lines.push('  box-shadow: var(--shadow-inner);');
  }
  lines.push('}');
  lines.push('');
  lines.push('.input:focus {');
  lines.push('  outline: none;');
  lines.push('  border-color: var(--color-brand);');
  lines.push(`  box-shadow: 0 0 0 3px color-mix(in srgb, var(--color-brand) 20%, transparent);`);
  lines.push('}');
  lines.push('');

  // Badge
  lines.push('.badge {');
  lines.push('  display: inline-flex;');
  lines.push('  align-items: center;');
  lines.push('  padding: var(--space-xs) var(--space-sm);');
  lines.push('  font-size: var(--text-micro);');
  lines.push('  font-weight: var(--font-bold);');
  lines.push('  border-radius: var(--radius-full);');
  lines.push('  background: var(--color-surface-muted);');
  lines.push('  color: var(--color-text-secondary);');
  lines.push('}');

  return lines.join('\n');
}

export default { generateCSS };
